Product/Website/src/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#import the edit_info views
from edit_info import views as edit_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),
    url(r'^edit/', include('edit_info.urls')),

    #login urls
    url(r'^accounts/login/$', edit_views.login, name='login'),
    url(r'^accounts/auth_login/$', edit_views.auth_login, name="auth_login"),
    url(r'^accounts/logout/$', edit_views.logout, name='logout'),

    #db update
    url(r"^update/", include("database_manager.urls")),
]

Product/Website/web/models.py
from django.db import models

#Model used for storing projects
class Project(models.Model):
    title = models.CharField(max_length = 120) #120 is up for discussion
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now = False, auto_now_add = True)
    degreeChoices = (('BSc','Bachelor'),('MS','Masters'))
    degree = models.CharField(max_length = 5, choices = degreeChoices, default='BSc')
    topic = models.CharField(max_length = 120) #120 is up for discussion

    def __str__(self):
        return self.title

class Counselor(models.Model):
    readonly_fields=('account_id',)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    studyArea = models.CharField(max_length=255)
    office = models.CharField(max_length=255)
    projects = models.ManyToManyField(Project)
    url = models.URLField(default="NOURL")
    accountId = models.IntegerField(default=-1)
    statusChoices = (('Available','Available'),('Unavailable','Unavailable'))
    status = models.CharField(max_length=50, choices=statusChoices, default='Available')


    def __str__(self):
        return self.name

    def is_registered(self):
        return not self.accountId == -1

Product/Website/web/templates/web/counselor_detail.html
{%extends "web/master.html" %}
{% block content%}
<title>Counselor detail</title>
<style>
p.colgreen {color:#1D8348}
p.colred {color:#E60000}
</style>

<div class="row info-box">

  <div class="col-md-3">
    <h2><small>Counselor details for</small><br />{{ counselor.name }}</h2>
  </div>

  <div class="col-md-3">
    <h2><small>Area of study</small><br />{{ counselor.study_area }}</h2>
  </div>

<!--   -->
  <div class="col-md-3">
    <h2><small>Status</small><br />
        {% if counselor.status == "Available" %}
        <p class="colgreen">Available</p>
        {% else %}
        <p class="colred">Unavailable</p>
        {% endif %}
    </h2>
  </div>


  <div class="col-md-3">
    <br />
    <h4><small>Email:  </small>{{ counselor.email }}</h4>
    <h4><small>Office:  </small>{{ counselor.office }}</h4>
  </div>

</div>
  <h2>Projects</h2>
<div style="position: relative; top: -30px;">
  <div class="row">
    <div class="col-md-4">
      <h3><small>Title</small></h3>
    </div>

    <div class="col-md-4">
      <h3><small>Topic</small></h3>
    </div>

    <div class="col-md-4">
      <h3><small>Degree</small></h3>
    </div>
  </div>

  <div class="list-group" id="counselor_projects_list">
    {% for project in counselor.projects.all%}
    <a class="list-group-item" href="{% url 'project_detail' project.id %}">
      <div class="row">
        <div class="col-md-4">{{ project.title }}</div>
        <div class="col-md-4">{{ project.topic }}</div>
        <div class="col-md-4">{{ project.degree }}</div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>


{% endblock %}

Product/Website/web/templates/web/counselor_list.html
{%extends "web/master.html" %}
{% block content%}
<title>Counselor overview</title>
<h1>List of councelors</h1>
  <div class="list-group">
  {% for counselor in counselors %}
    <a class="list-group-item" href="{% url 'counselor_detail' counselor.id %}">{{ counselor.name }}</a>
  {% endfor %}
</div>
{% endblock %}

Product/Website/web/templates/web/index.html
{%extends "web/master.html" %}
{% block content%}
<title>Home</title>
  <div class="row">
    <div class="col-md-12" style="width : 100%; height : 300px; opacity : 0.8; background-image : url('http://www.wilkes.edu/academics/colleges/arts-humanities-social-sciences/humanities/_images/English_1170x300.jpg');"></div>
  </div>
  <h1>Home</h1>
  <p>Welcome to Projects in Stock, a site made to help you choose a project for your master or bachelor project!</p><br />
  </span>
  <div class="content">
    {% if not user.is_authenticated %}
      <a href="{% url "login" %}" class="btn btn-info" role="button">Login for counselors</a>
    {% else %}
      <a href="{% url "logout" %}" class="btn btn-info" role="button">Logout</a>
    {% endif %}
  </div>
{%endblock%}

Product/Website/web/templates/web/master.html
<!DOCTYPE html>
<html>
<head>
  <!-- loading static files -->
  {% load staticfiles %}

  <!--custom rules-->
  <link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}"/>

  <!-- importing bootstrap-->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#content').fadeIn();
    });
  </script>
</head>
<body>
<div class="container" id="site-wrapper">
  <!--header-->
  <div class="row" id="header-wrap">
    <div class="col-md-9">
      <h2><small>University of Copenhagen</small> <br /><b>P</b>rojects <b>I</b>n <b> S</b>tock</h2>
    </div>
    <div class ="col-md-3">
      <ul class="nav nav-pills" id="menu">
        <li><a href="{% url "index" %}">Home</a></li>
        <li><a id="Counselor-list" href="{% url "counselor_list" %}">Counselors</a></li>
        <li><a id="Project-list" href="{% url "project_list" %}">Projects</a></li>
      </ul>
    </div>
  </div>
<div id="content" style="display: none;">
{%block content%}
{%endblock%}
</div>

<div class="row" id="footer">
  <div class="col-md-4">
    <h3>Useful Links</h3>
      <a href="{% url 'admin:index' %}">Admin Panel</a><br />
      <a href="{% url 'login' %}">Counselor Login</a><br />
      <a href="https://docs.djangoproject.com/en/1.9/">Django Documentation</a><br />
      <a href="http://getbootstrap.com/components/">Bootstrap Documentation</a><br />
      <a href="https://github.com/PhilipFraDIKU/Projects-in-Stock">Github Repo</a><br /><br />

  </div>
  <div class="col-md-4">
    <h3>Project by</h3>
      <h5>Philip Girelli</h5>
      <h5>Herluf Baggesen</h5>
      <h5>Mads Buchmann</h5>

  </div>
  <div class="col-md-4">
  <h3>Info</h3>
  <p>
   This page is not associated with the offical systems of Copenhagen University, and is the result of a student project.
  </p>
  </div>
</div>
</div>
</body>
</html>

Product/Website/web/templates/web/project_detail.html
{%extends "web/master.html" %}
{% block content%}
  <h2><small>Project details for</small> <br />{{ project.title }}</h2>
<br />
  <div class="row info-box">

  <div class="col-md-4">
    <h4>Topic</h4>
    <h3>{{ project.topic }}</h3>
  </div>

  <div class="col-md-4">
    <h4>Degree</h4>
    <h3>{{ project.degree }}</h3>
  </div>

  <div class="col-md-4">
    <h4>Counselors</h4>
      <div class="list-group">
      {% for counselor in project.counselor_set.all %}
        <a class="list-group-item" href="{% url 'counselor_detail' counselor.id %}">{{ c.name }}</a>
      {% endfor %}
    </div>
  </div>
  </div>

  <br />
  <h3>Project Description</h3>
  <div class="jumbotron">
  <p>{{ project.description }}</p>
  </div>
{%endblock%}

Product/Website/web/templates/web/project_list.html
{%extends "web/master.html" %}
{% block content%}
<title>Projects overview</title>
  <h1>List of projects</h1>
  <div class="list-group">
    {% for project in project_list %}
    <a class="list-group-item" href="{% url 'project_detail' project.id %}">{{project.title}}</a>
    {% endfor %}
  </div>
{%endblock%}